#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

# helper programs
mkdir -p $DESTDIR/lib/vdev
for prog in /lib/vdev/*; do

   # shell script or library?
   if [ -z "${prog#*.sh}" ]; then 

      cp -a $prog $DESTDIR/lib/vdev/
   else

      # binary?
      if [ -f $prog -a -x $prog ]; then 

         copy_exec $prog /lib/vdev
      fi
   fi
done

# config 
mkdir -p $DESTDIR/etc/vdev
cp -a /etc/vdev/* $DESTDIR/etc/vdev/

# the daemon itself 
copy_exec /sbin/vdevd

# blkid (needed by vdevd's helpers)
copy_exec /sbin/blkid

# lvm tools (needed by vdevd's helpers)
copy_exec /sbin/lvs
copy_exec /sbin/pvs
copy_exec /sbin/lvm

# network tools (needed by vdevd's helpers)
copy_exec /bin/ip
copy_exec /sbin/ip

# SELinux tools
copy_exec /sbin/restorecon || true

# device tools
copy_exec /sbin/MAKEDEV || true

# device mapper tools
copy_exec /sbin/dmsetup 

# GNU tools (not the busybox equivalents)
copy_exec /bin/sed
copy_exec /bin/grep 
copy_exec /bin/fgrep
copy_exec /bin/egrep 
copy_exec /bin/chown /bin/vdev-chown 
copy_exec /bin/chmod /bin/vdev-chmod

# Linux tools
copy_exec /bin/kmod 

# users and groups databases
cp -a /etc/passwd $DESTDIR/etc/passwd
cp -a /etc/group $DESTDIR/etc/group

# since vdevd is multi-threaded, libpthread will dynamically load libgcc_s
# (and copy_exec won't detect this)
copy_exec /lib/`gcc -print-multiarch`/libgcc_s.so.1
