#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

if [ -w /sys/kernel/uevent_helper ]; then
	echo > /sys/kernel/uevent_helper
fi

/sbin/vdevd -c /etc/vdev/vdevd.conf -l /run/vdevd.boot.log -p /run/vdevd.boot.pid /dev

# If the rootdelay parameter has been set, we wait a bit for devices
# like usb/firewire disks to settle.
if [ "$ROOTDELAY" ]; then
	sleep $ROOTDELAY
fi

# Leave vdevd running to process events that come in out-of-band (like USB
# connections)
