#!/bin/sh 

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

if [ -w /sys/kernel/uevent_helper ]; then
	echo > /sys/kernel/uevent_helper
fi

/bin/mkdir -p /run/vdev/
/sbin/vdevd -c /etc/vdev/vdevd.conf -l /run/vdev/vdevd.boot.log -p /run/vdevd.boot.pid -v2 /dev

if [ -d /dev/metadata/udev ] && ! [ -e /run/udev ]; then 
   /bin/ln -s /dev/metadata/udev /run/udev || true 
fi

# If the rootdelay parameter has been set, we wait a bit for devices
# like usb/firewire disks to settle.
if [ "$ROOTDELAY" ]; then
	sleep $ROOTDELAY
fi

# Leave vdevd running to process events that come in out-of-band (like USB
# connections)
