#!/bin/sh

# set up /dev/input/by-id and /dev/input/by-path

. $VDEV_HELPERS/subr.sh

# full sysfs path
SYSFS_PATH=$VDEV_OS_SYSFS_MOUNTPOINT/$VDEV_OS_DEVPATH

# if we don't know the device path, then there's not much we can do...
if [ "$VDEV_PATH" = "UNKNOWN" ]; then 
   exit 0
fi

# if removing, just blow away the symlinks
if [ "$VDEV_ACTION" = "remove" ]; then 
   
   remove_links $VDEV_METADATA
   exit 0
fi

# make sure we're adding...
if [ "$VDEV_ACTION" != "add" ]; then 
   
   fail 10 "Unknown action '$VDEV_ACTION'"
fi

# stat the device!
eval $($VDEV_HELPERS/stat_input $VDEV_MOUNTPOINT/$VDEV_PATH)
STAT_RC=$?

# succeeded?
test 0 -ne $STAT_RC && fail 2 "stat_input $VDEV_PATH exit code $STAT_RC"

# get the persistent path for this device 
eval $($VDEV_HELPERS/stat_path $VDEV_MOUNTPOINT/$VDEV_PATH)
STAT_RC=$?

# succeeded?
test 0 -ne $STAT_RC && fail 2 "stat_path $VDEV_PATH exit code $STAT_RC" 

# no path?
test -z "$VDEV_PERSISTENT_PATH" && exit 0

# input class?
INPUT_CLASS=$VDEV_INPUT_CLASS

if [ -z "$INPUT_CLASS" ]; then 
   
   # not a mouse, keyboard, or joystick.
   # pcspkr?
   INPUT_CLASS=$(test -n "$(drivers $SYSFS_PATH | /bin/grep "pcspkr")" && echo "spkr")
fi

if [ -z "$INPUT_CLASS" -a -f $SYSFS_PATH/name ]; then 
   
   # not a mouse, keyboard, joystick, or PC speaker 
   # ir device?  check the sysfs name
   INPUT_CLASS=$(/bin/cat $SYSFS_PATH/name | /bin/grep -i "dvb")
   if [ -n "$INPUT_CLASS" ]; then 
      
      INPUT_CLASS="ir"
   else 

      INPUT_CLASS=$(/bin/cat $SYSFS_PATH/name | /bin/grep " IR ")
      if [ -n "$INPUT_CLASS" ]; then 
      
         INPUT_CLASS="ir"
      fi
   fi
fi

# allow empty input class for event device nodes generated by platform and usb devices...
if [ -z "$INPUT_CLASS" -a -n "$(subsystems $SYSFS_PATH | /bin/egrep "usb|platform")" -a -n "$(echo $VDEV_OS_DEVNAME | /bin/egrep "event*")" ]; then 

   add_link ../../$VDEV_PATH $VDEV_MOUNTPOINT/input/by-path/$VDEV_PERSISTENT_PATH-event $VDEV_METADATA

elif [ -n "$INPUT_CLASS" ]; then

   # non-empty input class...
   # event?
   if [ -n "$(echo $VDEV_OS_DEVNAME | /bin/egrep "event*")" ]; then 

      add_link ../../$VDEV_PATH $VDEV_MOUNTPOINT/input/by-path/$VDEV_PERSISTENT_PATH-event-$INPUT_CLASS $VDEV_METADATA
   else 

      add_link ../../$VDEV_PATH $VDEV_MOUNTPOINT/input/by-path/$VDEV_PERSISTENT_PATH-$INPUT_CLASS $VDEV_METADATA
   fi
fi

exit 0
